### ISSUE TITLE
There are no bindings for group chats

### ISSUE THREAD

**Issue by longnetwork** [TokTok/py-toxcore-c#121]
What is the difference between conferences and groups?

**Comment by iphydf** [comment]
https://github.com/TokTok/py-toxcore-c/blob/master/pytox%2Ftoxcore%2Ftox.pyx#L922 this is where group chats bindings start.

Groups are dht based group chats that you can join by id, have moderator functionality (kick, mute, etc), secret identities (can't know the person's tox id) and a lot more (e.g. custom packets).

Conferences are friend connection based without all that functionality. They are an older implementation of groups that we keep around for backward compatibility.

**Comment by longnetwork** [comment]
Thank you!
