### ISSUE TITLE
toxav_new not found

### ISSUE THREAD

**Issue by opensourcer2** [TokTok/py-toxcore-c#52]
I am trying to build against `toxcore` version `0.2.10` but I got error that `toxav_new` not found and so AV support is disabled.  Which version of `toxcore` is PyTox built against?

**Comment by iphydf** [comment]
https://travis-ci.com/github/TokTok/py-toxcore-c/jobs/319847638#L330 says AV can be found. How are you building toxcore? If you use cmake, can you try passing `-DMUST_BUILD_TOXAV=ON` to cmake to make sure toxav is actually being built? This is how we build it on the CI: https://travis-ci.com/github/TokTok/py-toxcore-c/jobs/319847788#L356

**Comment by opensourcer2** [comment]
I am trying to build a debian package using `debuild`.  The symbol `toxav_new` does exist in `libtoxav.so` but not in `libtoxcore.so`.  The code in `setup.py` check `libtoxcore.so` and so does not see it.  Is `toxav_new` suppose to exist in `libtoxcore.so`?

**Comment by iphydf** [comment]
Can you check if https://github.com/TokTok/py-toxcore-c/pull/54 fixes it for you?

**Comment by opensourcer2** [comment]
> Can you check if #54 fixes it for you?

Yes that fixed it. Thank you.
